/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca.maplepost.jlauncher;

import java.awt.Desktop;
import java.awt.desktop.AboutEvent;
import java.awt.desktop.AboutHandler;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author peterslack
 */
public class JLauncherUi extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(JLauncherUi.class.getName());

    
    
    /**
     * Creates new form JLauncherUi
     */
    public JLauncherUi() {
        initComponents();
       // test();
    }

    public void test()  {
        if (true)
            throw new RuntimeException("Test runtime exception");
    }
     public void initDesktop() {
    
        
        if (Desktop.isDesktopSupported()) {
        LOG.log(Level.INFO, "DESKTOP IS SUPPORTED");
            Desktop dt = Desktop.getDesktop();
           // dt.setAboutHandler(ah);
            
        } else {
            LOG.log(Level.INFO, "DESKTOP NOT SUPPORTED");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLauncherUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLauncherUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLauncherUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLauncherUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        final JLauncherUi jlui = new JLauncherUi();
        if(Desktop.isDesktopSupported()) {
            jlui.initDesktop();
        }
        LOG.log(Level.INFO,"thread name " + Thread.currentThread().getName());
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LOG.log(Level.INFO,"ev queue thread name " + Thread.currentThread().getName());
                jlui.setVisible(true);
            }
        });
    }

    private final AboutHandler ah = new AboutHandler() {
        @Override
        public void handleAbout(AboutEvent e) {
            LOG.log(Level.INFO,"ABOUT ME MF");
        }
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
